
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    
  backend:
    build: ./backend
    container_name: backend-app
    restart: always
    ports:
      - "5000:81"
    # depends_on:
    #   - mysql
    environment:
     DB_HOST: mysql
     DB_USER: myuser
     DB_NAME: mydatabase
     DB_PASSWORD: mypassword
    volumes:
      - ./backend:/app
    networks:
      - app-network
    

  frontend:
    build: ./frontend
    container_name: frontend-app
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
